# Generated by Django 4.2.5 on 2025-11-05 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('number_of_guests', models.IntegerField(default=0, verbose_name="Nombre d'invités")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Temp')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitation', verbose_name='Invité')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
            },
        ),
    ]
