# Generated by Django 4.2.5 on 2025-11-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visiteur', 'verbose_name_plural': 'Visiteurs'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_of_guests',
            field=models.IntegerField(default=0, verbose_name="Nombre d'invités"),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='job',
            field=models.CharField(max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitation', verbose_name='Invité'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Temp'),
        ),
    ]
