# Generated by Django 4.2.5 on 2025-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
