# Generated by Django 4.2.5 on 2025-11-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_visitor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client Name'),
        ),
    ]
