# Generated by Django 4.2.5 on 2025-11-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_client_number_of_guests_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Initiation',
            new_name='Invitation',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
