# Generated by Django 4.2.5 on 2025-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_visitor_options_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
