# Generated by Django 4.2.5 on 2025-11-05 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_visitor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
        migrations.CreateModel(
            name='InvitationItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('invitaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitation')),
            ],
        ),
    ]
