# Generated by Django 4.2.5 on 2025-11-03 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_rename_initiation_invitation_alter_client_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='barcode_base64',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='code',
            field=models.CharField(default='555', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
