# Generated by Django 4.2.5 on 2025-11-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_remove_invitation_code_remove_visitor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationitems',
            old_name='invitaion',
            new_name='invitation',
        ),
    ]
