# Generated by Django 4.2.5 on 2025-11-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitation'),
        ),
    ]
