# Generated by Django 4.2.5 on 2025-11-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_rename_invitaion_invitationitems_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.invitationitems', verbose_name='Invité'),
        ),
    ]
