# Generated by Django 4.2.5 on 2025-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_client_id_alter_invitation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='barcode_base64',
        ),
    ]
